FROM --platform=$BUILDPLATFORM docker.io/library/golang:1.22@sha256:d5302d40dc5fbbf38ec472d1848a9d2391a13f93293a6a5b0b87c99dc0eaa6ae as build

ARG TARGETOS
ARG TARGETARCH

ADD . /src
WORKDIR /src

RUN make build

FROM docker.io/library/alpine:3.19@sha256:c5b1261d6d3e43071626931fc004f70149baeba2c8ec672bd4f27761f8e1ad6b

LABEL maintainer="Robert Kaussow <mail@thegeeklab.de>"
LABEL org.opencontainers.image.authors="Robert Kaussow <mail@thegeeklab.de>"
LABEL org.opencontainers.image.title="wp-git-action"
LABEL org.opencontainers.image.url="https://github.com/thegeeklab/wp-git-action"
LABEL org.opencontainers.image.source="https://github.com/thegeeklab/wp-git-action"
LABEL org.opencontainers.image.documentation="https://github.com/thegeeklab/wp-git-action"

RUN apk --update add --no-cache git rsync && \
    rm -rf /var/cache/apk/* && \
    rm -rf /tmp/*

COPY --from=build /src/dist/wp-git-action /bin/wp-git-action
ENTRYPOINT ["/bin/wp-git-action"]
