FROM --platform=$BUILDPLATFORM docker.io/library/golang:1.23.3@sha256:73f06be4578c9987ce560087e2e2ea6485fb605e3910542cadd8fa09fc5f3e31 AS build

ARG TARGETOS
ARG TARGETARCH

ADD . /src
WORKDIR /src

RUN make build

FROM docker.io/library/alpine:3.20@sha256:1e42bbe2508154c9126d48c2b8a75420c3544343bf86fd041fb7527e017a4b4a

LABEL maintainer="Robert Kaussow <mail@thegeeklab.de>"
LABEL org.opencontainers.image.authors="Robert Kaussow <mail@thegeeklab.de>"
LABEL org.opencontainers.image.title="wp-git-action"
LABEL org.opencontainers.image.url="https://github.com/thegeeklab/wp-git-action"
LABEL org.opencontainers.image.source="https://github.com/thegeeklab/wp-git-action"
LABEL org.opencontainers.image.documentation="https://github.com/thegeeklab/wp-git-action"

RUN apk --update add --no-cache git rsync && \
    rm -rf /var/cache/apk/* && \
    rm -rf /tmp/*

COPY --from=build /src/dist/wp-git-action /bin/wp-git-action
ENTRYPOINT ["/bin/wp-git-action"]
