FROM --platform=$BUILDPLATFORM golang:1.20@sha256:02d4d8887131f2fea51bb380835917bd605dc2af1ac4ff90012fdaecf87fe10c as build

ARG TARGETOS
ARG TARGETARCH

ADD . /src
WORKDIR /src

RUN make build

FROM alpine:3.18@sha256:02bb6f428431fbc2809c5d1b41eab5a68350194fb508869a33cb1af4444c9b11

LABEL maintainer="Robert Kaussow <mail@thegeeklab.de>"
LABEL org.opencontainers.image.authors="Robert Kaussow <mail@thegeeklab.de>"
LABEL org.opencontainers.image.title="drone-git-action"
LABEL org.opencontainers.image.url="https://github.com/thegeeklab/drone-git-action"
LABEL org.opencontainers.image.source="https://github.com/thegeeklab/drone-git-action"
LABEL org.opencontainers.image.documentation="https://github.com/thegeeklab/drone-git-action"

RUN apk --update add --no-cache git rsync && \
    rm -rf /var/cache/apk/* && \
    rm -rf /tmp/*

COPY --from=build /src/dist/drone-git-action /bin/drone-git-action
ENTRYPOINT ["/bin/drone-git-action"]
