FROM --platform=$BUILDPLATFORM golang:1.20@sha256:52921e63cc544c79c111db1d8461d8ab9070992d9c636e1573176642690c14b5 as build

ARG TARGETOS
ARG TARGETARCH

ADD . /src
WORKDIR /src

RUN make build

FROM alpine:3.17@sha256:69665d02cb32192e52e07644d76bc6f25abeb5410edc1c7a81a10ba3f0efb90a

LABEL maintainer="Robert Kaussow <mail@thegeeklab.de>"
LABEL org.opencontainers.image.authors="Robert Kaussow <mail@thegeeklab.de>"
LABEL org.opencontainers.image.title="drone-git-action"
LABEL org.opencontainers.image.url="https://github.com/thegeeklab/drone-git-action"
LABEL org.opencontainers.image.source="https://github.com/thegeeklab/drone-git-action"
LABEL org.opencontainers.image.documentation="https://github.com/thegeeklab/drone-git-action"

RUN apk --update add --no-cache git rsync && \
    rm -rf /var/cache/apk/* && \
    rm -rf /tmp/*

COPY --from=build /src/dist/drone-git-action /bin/drone-git-action
ENTRYPOINT ["/bin/drone-git-action"]
