FROM alpine:3.17@sha256:f271e74b17ced29b915d351685fd4644785c6d1559dd1f2d4189a5e851ef753a

LABEL maintainer="Robert Kaussow <mail@thegeeklab.de>"
LABEL org.opencontainers.image.authors="Robert Kaussow <mail@thegeeklab.de>"
LABEL org.opencontainers.image.title="drone-git-action"
LABEL org.opencontainers.image.url="https://github.com/thegeeklab/drone-git-action"
LABEL org.opencontainers.image.source="https://github.com/thegeeklab/drone-git-action"
LABEL org.opencontainers.image.documentation="https://github.com/thegeeklab/drone-git-action"

RUN apk --update add --no-cache git rsync && \
    rm -rf /var/cache/apk/* && \
    rm -rf /tmp/*

ADD dist/drone-git-action /bin/

ENTRYPOINT ["/bin/drone-git-action"]
