---
when:
  - event: [tag]
  - event: [push, manual]
    branch:
      - ${CI_REPO_DEFAULT_BRANCH}

steps:
  - name: publish-dockerhub
    image: quay.io/thegeeklab/wp-docker-buildx:6
    depends_on: [security-scan]
    settings:
      auto_tag: true
      containerfile: Containerfile.multiarch
      password:
        from_secret: docker_password
      platforms:
        - linux/amd64
        - linux/arm64
      provenance: false
      repo: ${CI_REPO}
      username:
        from_secret: docker_username

  - name: publish-quay
    image: quay.io/thegeeklab/wp-docker-buildx:6
    depends_on: [security-scan]
    settings:
      auto_tag: true
      containerfile: Containerfile.multiarch
      password:
        from_secret: quay_password
      platforms:
        - linux/amd64
        - linux/arm64
      provenance: false
      registry: quay.io
      repo: quay.io/${CI_REPO}
      username:
        from_secret: quay_username

depends_on:
  - test
