---
when:
  - event: [pull_request, tag]
  - event: [push, manual]
    branch:
      - ${CI_REPO_DEFAULT_BRANCH}
  - event: [push]
    branch:
      - renovate/*

steps:
  - name: markdownlint
    image: quay.io/thegeeklab/markdownlint-cli
    group: test
    commands:
      - markdownlint 'README.md' 'CONTRIBUTING.md'

  - name: spellcheck
    image: quay.io/thegeeklab/alpine-tools
    group: test
    commands:
      - spellchecker --files 'docs/**/*.md' 'README.md' 'CONTRIBUTING.md' -d .dictionary -p spell indefinite-article syntax-urls
    environment:
      FORCE_COLOR: "true"

  - name: link-validation
    image: docker.io/lycheeverse/lychee
    group: test
    commands:
      - lychee --no-progress --format detailed docs/content README.md

  - name: publish
    image: quay.io/thegeeklab/wp-git-action
    settings:
      action:
        - pages
      author_email: bot@thegeeklab.de
      author_name: thegeeklab-bot
      branch: docs
      message: "[skip ci] auto-update documentation"
      netrc_password:
        from_secret: github_token
      pages_directory: docs/
    when:
      - event: [push, manual]
        branch:
          - ${CI_REPO_DEFAULT_BRANCH}
        status: [success, failure]

  - name: pushrm-dockerhub
    image: docker.io/chko/docker-pushrm:1
    secrets:
      - source: docker_password
        target: DOCKER_PASS
      - source: docker_username
        target: DOCKER_USER
    environment:
      PUSHRM_FILE: README.md
      PUSHRM_SHORT: Woodpecker CI plugin to perform git actions
      PUSHRM_TARGET: ${CI_REPO}
    when:
      - event: [push, manual]
        branch:
          - ${CI_REPO_DEFAULT_BRANCH}
        status: [success]

  - name: pushrm-quay
    image: docker.io/chko/docker-pushrm:1
    secrets:
      - source: quay_token
        target: APIKEY__QUAY_IO
    environment:
      PUSHRM_FILE: README.md
      PUSHRM_TARGET: quay.io/${CI_REPO}
    when:
      - event: [push, manual]
        branch:
          - ${CI_REPO_DEFAULT_BRANCH}
        status: [success]

depends_on:
  - build-package
  - build-container
