---
when:
  - event: [pull_request, tag]
  - event: [push, manual]
    branch:
      - ${CI_REPO_DEFAULT_BRANCH}

steps:
  deps:
    image: docker.io/library/golang:1.21
    commands:
      - make deps

  lint:
    image: docker.io/library/golang:1.21
    commands:
      - make lint

  test:
    image: docker.io/library/golang:1.21
    commands:
      - make test
